### ISSUE TITLE
railway的PostgreSQL数据库初始化失败

### ISSUE THREAD

**Issue by zxmacc** [walinejs/railway-starter#1]
![A(RZO`29K(`U%E)1OIHOH0](https://user-images.githubusercontent.com/71143103/162602327-ce083606-269b-4f3c-a0aa-a6511a0eb01b.png)

**Comment by zxmacc** [comment]
## 下方显示
CREATE SEQUENCE wl_comment_seq; CREATE TABLE wl_comment ( id int check (id > 0) NOT NULL DEFAULT NEXTVAL ('wl_comment_seq'), user_id int DEFAULT NULL, comment text, insertedAt timestamp(0) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, ip varchar(100) DEFAULT '', link varchar(255) DEFAULT NULL, mail varchar(255) DEFAULT NULL, nick varchar(255) DEFAULT NULL, pid int DEFAULT NULL, rid int DEFAULT NULL, sticky boolean DEFAULT NULL, status varchar(50) NOT NULL DEFAULT '', ua text, url varchar(255) DEFAULT NULL, createdAt timestamp(0) with time zone NULL DEFAULT CURRENT_TIMESTAMP, updatedAt timestamp(0) with time zone NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id) ) ; CREATE SEQUENCE wl_counter_seq; CREATE TABLE wl_counter ( id int check (id > 0) NOT NULL DEFAULT NEXTVAL ('wl_counter_seq'), time int DEFAULT NULL, url varchar(255) NOT NULL DEFAULT '', createdAt timestamp(0) with time zone NULL DEFAULT CURRENT_TIMESTAMP, updatedAt timestamp(0) with time zone NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id) ) ; CREATE SEQUENCE wl_users_seq; CREATE TABLE wl_users ( id int check (id > 0) NOT NULL DEFAULT NEXTVAL ('wl_users_seq'), display_name varchar(255) NOT NULL DEFAULT '', email varchar(255) NOT NULL DEFAULT '', password varchar(255) NOT NULL DEFAULT '', type varchar(50) NOT NULL DEFAULT '', url varchar(255) DEFAULT NULL, avatar varchar(255) DEFAULT NULL, github varchar(255) DEFAULT NULL, twitter varchar(255) DEFAULT NULL, facebook varchar(255) DEFAULT NULL, google varchar(255) DEFAULT NULL, weibo varchar(255) DEFAULT NULL, qq varchar(255) DEFAULT NULL, 2fa varchar(32) DEFAULT NULL, createdAt timestamp(0) with time zone NULL DEFAULT CURRENT_TIMESTAMP, updatedAt timestamp(0) with time zone NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id) ) ; - syntax error at or near "2"

**Comment by zxmacc** [comment]
试过重新部署，还是一样的问题，不清楚错在哪里QwQ
一开始部署的变量没有动过，设置的私有仓库
部署完后直接根据教程初始化就这样了

**Comment by lizheming** [comment]
更新了下建表语句，再试一下
